version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - backend
      - frontend
  appointment:
    build: ./appointment
    restart: always
    hostname: appointment
    env_file:
      - .env
    networks:
      - backend
  class:
    build: ./class
    restart: always
    hostname: class
    env_file:
      - .env
    networks:
      - backend
  client:
    build: ./client
    restart: always
    hostname: client
    env_file:
      - .env
    networks:
      - backend
  enrrollment:
    build: ./enrrollment
    restart: always
    hostname: enrrollment
    env_file:
      - .env
    networks:
      - backend
  patient:
    build: ./patient
    restart: always
    hostname: patient
    env_file:
      - .env
    networks:
      - backend
  sale:
    build: ./sale
    restart: always
    hostname: sale
    env_file:
      - .env
    networks:
      - backend
  token:
    build: ./token
    restart: always
    hostname: token
    env_file:
      - .env
    networks:
      - backend
  user:
    build: ./user
    restart: always
    hostname: user
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure