// Generated by https://quicktype.io

export interface IAppointment {
  GenderPreference: string;
  Duration: number;
  ProviderId: string;
  Id: number;
  Status: string;
  StartDateTime: string;
  EndDateTime: string;
  Notes: null;
  StaffRequested: boolean;
  ProgramId: number;
  SessionTypeId: number;
  LocationId: number;
  StaffId: number;
  ClientId: string;
  FirstAppointment: boolean;
  ClientServiceId: null;
  Resources: null;
  AddOns: null;
  OnlineDescription: string;
}
