// Generated by https://quicktype.io

import { IClient } from './client.interface';

export interface IClass {
  ClassScheduleId: number;
  Visits: null;
  Clients: IClient[];
  Location: Location;
  Resource: Resource;
  MaxCapacity: number;
  WebCapacity: number;
  TotalBooked: number;
  TotalSignedIn: number;
  TotalBookedWaitlist: number;
  WebBooked: number;
  SemesterId: null;
  IsCanceled: boolean;
  Substitute: boolean;
  Active: boolean;
  IsWaitlistAvailable: boolean;
  IsEnrolled: null;
  HideCancel: boolean;
  Id: number;
  IsAvailable: boolean;
  StartDateTime: string;
  EndDateTime: string;
  LastModifiedDateTime: string;
  ClassDescription: ClassDescription;
  Staff: Staff;
  BookingWindow: BookingWindow;
  BookingStatus: string;
  VirtualStreamLink: null;
}

export interface BookingWindow {
  StartDateTime: string;
  EndDateTime: string;
  DailyStartTime: null;
  DailyEndTime: null;
}

export interface ClassDescription {
  Active: boolean;
  Description: string;
  Id: number;
  ImageURL: string;
  LastUpdated: string;
  Level: Level;
  Name: string;
  Notes: string;
  Prereq: string;
  Program: Program;
  SessionType: SessionType;
  Category: null;
  CategoryId: null;
  Subcategory: null;
  SubcategoryId: null;
}

export interface Level {
  Id: number;
  Name: string;
  Description: null;
}

export interface Program {
  Id: number;
  Name: string;
  ScheduleType: string;
  CancelOffset: number;
  ContentFormats: string[];
}

export interface SessionType {
  Type: string;
  DefaultTimeLength: null;
  StaffTimeLength: null;
  Id: number;
  Name: string;
  NumDeducted: number;
  ProgramId: number;
}

export interface Location {
  AdditionalImageURLs: null;
  Address: string;
  Address2: string;
  Amenities: Resource[];
  BusinessDescription: null;
  City: string;
  Description: null;
  HasClasses: boolean;
  Id: number;
  Latitude: number;
  Longitude: number;
  Name: string;
  Phone: string;
  PhoneExtension: null;
  PostalCode: string;
  SiteID: number;
  StateProvCode: string;
  Tax1: number;
  Tax2: number;
  Tax3: number;
  Tax4: number;
  Tax5: number;
  TotalNumberOfRatings: number;
  AverageRating: number;
  TotalNumberOfDeals: number;
}

export interface Resource {
  Id: number;
  Name: string;
}

export interface Staff {
  Address: null;
  AppointmentInstructor: boolean;
  AlwaysAllowDoubleBooking: boolean;
  Bio: string;
  City: null;
  Country: string;
  Email: null;
  FirstName: string;
  HomePhone: null;
  Id: number;
  IndependentContractor: boolean;
  IsMale: boolean;
  LastName: string;
  MobilePhone: null;
  Name: string;
  PostalCode: null;
  ClassTeacher: boolean;
  SortOrder: number;
  State: string;
  WorkPhone: null;
  ImageUrl: string;
  ClassAssistant: boolean;
  ClassAssistant2: boolean;
  EmploymentStart: null;
  EmploymentEnd: null;
  ProviderIDs: null;
  Rep: boolean;
  Rep2: boolean;
  Rep3: boolean;
  Rep4: boolean;
  Rep5: boolean;
  Rep6: boolean;
  Appointments: any[];
  Unavailabilities: any[];
  Availabilities: any[];
  EmpID: null;
}
